### ISSUE TITLE
numpy Singular matrix error while finding reseaus

### ISSUE THREAD

**Issue by TristanBlus** [iamdonovan/sPyMicMac#10]
When using find_reseau_grid command, sometimes it will report an error of: numpy.linalg.LinAlgError: Singular matrix.  Is it a bug? Or just because of the low image quality?

Also, in some cases, the calculated distortion fields were obvious wrong or contained a few distortion vectors (as the picture show).

Here is the error information:

```
Finding grid points in DZB1211-500125L006001_b.tif...
Traceback (most recent call last):
  File "/usr/local/miniconda3/bin/find_reseau_grid", line 33, in <module>
    sys.exit(load_entry_point('spymicmac', 'console_scripts', 'find_reseau_grid')())
  File "/usr/local/sPyMicMac/spymicmac/tools/find_reseau_grid.py", line 25, in main
    find_reseau_grid(args.fn_img,
  File "/usr/local/sPyMicMac/spymicmac/image.py", line 964, in find_reseau_grid
    ux = lsq_fit(gcps_df.search_j.values, gcps_df.search_i.values, gcps_df.match_j.values)
  File "/usr/local/sPyMicMac/spymicmac/image.py", line 719, in lsq_fit
    fit = (A.T * A).I * A.T * b.T
  File "/usr/local/miniconda3/lib/python3.8/site-packages/numpy/matrixlib/defmatrix.py", line 835, in I
    return asmatrix(func(self))
  File "<__array_function__ internals>", line 5, in inv
  File "/usr/local/miniconda3/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 545, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 88, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix
``
![DZB1211-500142L008001_b_matches](https://user-images.githubusercontent.com/37327637/157366425-8be59eac-dc2c-4cfe-92ab-f1b953b538b1.png)

**Comment by gyp-1991-gq** [comment]
I made the same mistake!

**Comment by gyp-1991-gq** [comment]
I succeeded, but I did not remove the cross hairs.

**Comment by iamdonovan** [comment]
It's most likely because the first step (finding the border of the image) failed. 

I'll try to have a look at this sometime this week to see if I can't  figure out a way to improve that step.

**Comment by iamdonovan** [comment]
Try this with the changes in https://github.com/iamdonovan/sPyMicMac/commit/18d5ff0418452d2f2102c244495d7a03da73ecca - I tested find_reseau_grid on both DZB1211-500125L006001_a.tif and DZB1211-500125L006001_b.tif, with no errors.

**Comment by TristanBlus** [comment]
> 

Tnanks, Bob. I have test the changes, it works with no errors output. However, I found that the extracted reseau grid was obviously wrong.  Besides, this is not a occasional issue,  because I found 3 out of 4 test images were like this
![DZB1211-500125L006001_b_matches](https://user-images.githubusercontent.com/37327637/158929986-cb4b51f3-1aad-42e3-8b3a-2c935d0fca01.png)
.

**Comment by gyp-1991-gq** [comment]
We are looking at the same area, the Geladandong area.

**Comment by iamdonovan** [comment]
what are your other test images?

**Comment by gyp-1991-gq** [comment]
I have the same problem now. Please help me! thank you.

**Comment by iamdonovan** [comment]
Closing this as inactive.
