### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by gyp-1991-gq** [iamdonovan/sPyMicMac#11]
![image](https://user-images.githubusercontent.com/76198536/158123596-ae8179e1-4e83-492f-868b-239551a4ba85.png)
![image](https://user-images.githubusercontent.com/76198536/158123647-4b4d03a0-eba7-4140-b765-51adfe8ca171.png)
What is the cause of this error? Please help me, thank you!

**Comment by iamdonovan** [comment]
This looks either like an issue with the filename/path that you're using, or that 'Ori-InterneScan' hasn't been created. Can you check whether 'Ori-InterneScan' exists in the directory after you run the script, and let me know what filename  you're feeding to image.find_reseau_grid()?

**Comment by gyp-1991-gq** [comment]
Thank you very much for your answer! I have solved the problem.

**Comment by gyp-1991-gq** [comment]
When I run find_reseau_grid DZB1211-500125L005001_a.tif,  I get an error.
![image](https://user-images.githubusercontent.com/76198536/158718776-f1124b55-6809-438e-874d-89decb9b4cfe.png)
If I try to ignore this error, run the remove_cross command. Unfortunately, the cross on the image cannot be removed. Please help me, thank you!

**Comment by iamdonovan** [comment]
Right, because remove_cross depends on the output of find_reseau_grid.

Do you see the white line near the top of the image, outside of the border? Try cropping the image to remove that.

**Comment by gyp-1991-gq** [comment]
Can this step be operated directly in ArcGIS? Or which command of micmac? Thank you very much!

**Comment by gyp-1991-gq** [comment]
![image](https://user-images.githubusercontent.com/76198536/158761129-2babfaab-8ee9-4b19-a8f9-f7d08cb08f0f.png)
Is it this white line?

**Comment by iamdonovan** [comment]
Yes, it's that white line. You might be able to do it in ArcGIS, but for [gdal_translate](https://gdal.org/programs/gdal_translate.html) it would be something like:

> `gdal_translate -srcwin 0 yoff xsize (ysize-yoff) in.tif out.tif`

where yoff is the line where the line ends, and (xsize, ysize) are the size of the image in (columns, rows).

**Comment by gyp-1991-gq** [comment]
Thank you very much!

**Comment by gyp-1991-gq** [comment]
![image](https://user-images.githubusercontent.com/76198536/158811016-7724011d-2c86-4c76-89c6-00cc972ccb33.png)
![image](https://user-images.githubusercontent.com/76198536/158811101-a4c0778f-7586-4156-ab97-7d92b83b1784.png)
![Uploading image.png…]()
I successfully ran the relevant command, but I still didn't remove the "cross". Why is that?

**Comment by iamdonovan** [comment]
Try this with the changes in 18d5ff0418452d2f2102c244495d7a03da73ecca - I tested find_reseau_grid on both DZB1211-500125L005001_a.tif and DZB1211-500125L005001_b.tif, with no errors.

**Comment by gyp-1991-gq** [comment]
Can you tell me the parameters you entered with gdal_translate -srcwin clipping? Please help me, thank you!

**Comment by gyp-1991-gq** [comment]
Are images clipped before running Generate_MICMAC_measures -joined?

**Comment by gyp-1991-gq** [comment]
Why do I get an error <tifffile.TiffFile 'DZB1211-500125L005001_a_c.tif'> shaped series shape does not match page shape running find_reseau_grid DZb1211-500125L005001_a_c.tif after clipping?
I also get another error C: Miniconda3 envs KH9 lib site-packages matplotlib quiver.py:671: RuntimeWarning: Mean of empty slice.
mean = a [~ self.Umask].mean ()
![image](https://user-images.githubusercontent.com/76198536/158931709-b6fae4cd-405b-473d-89ad-20b22c939617.png)

**Comment by gyp-1991-gq** [comment]
There are no red arrows in the matching image.

**Comment by iamdonovan** [comment]
> Can you tell me the parameters you entered with gdal_translate -srcwin clipping? Please help me, thank you!

I didn't clip the images before running - the change to image.get_rough_frame in https://github.com/iamdonovan/sPyMicMac/commit/18d5ff0418452d2f2102c244495d7a03da73ecca should eliminate the need to clip the image beforehand.

> Why do I get an error <tifffile.TiffFile 'DZB1211-500125L005001_a_c.tif'> shaped series shape does not match page shape running find_reseau_grid DZb1211-500125L005001_a_c.tif after clipping?

This isn't an error, it's a warning. My guess is that gdal_translate didn't update the metadata tags, but it shouldn't have any actual effect on the output.

**Comment by gyp-1991-gq** [comment]
Thank you very much for your patient answer.
