### ISSUE TITLE
Error: find_reseau_grid()

### ISSUE THREAD

**Issue by ice-man-dahe** [iamdonovan/sPyMicMac#14]
Dear Prof. Bob McNabb,
 
Hope you have a pleasant day.
 
I am a graduate student of Yunnan University in China. My research is focus on surge-type glacier. I have tried to run your source program for a long time, but no progress. I am wondering if you could kindly provide me some guide. My question is as follows:

1) The generate_micmac_measures() command can only generate id_fiducial.txt, MeasuresCamera.xml, and Tmp-SL-Glob.xml, but before running the [find_reseau_grid](https://spymicmac.readthedocs.io/en/v0.1.1/spymicmac/scripts/find_reseau_grid.html)() command,  How is the MeasuresIm-DZB1215-500425L002001.tif.xml. generated?  In other words, how do I get the MeasuresIm-DZB1215-500425L002001.tif-S2D.xml file before I run the find_reseau_grid() command?
![image](https://user-images.githubusercontent.com/103547509/163093085-6cbdba4f-55c2-4bf1-b89e-63ec379b11ac.png)
2) When I run find_reseau_grid(), there are no errors.  However, as shown in the figure below, this result obviously looks wrong. How can I interpret the results or modify them to make reasonable?  Is this result related to the file (such as id_fiducial.txt, MeasuresCamera.xml, Tmp-SL-Glob.xml) generated in the previous step? Or is it related to MeasuresIm-DZB1215-500425L002001.tif.xml?
![image](https://user-images.githubusercontent.com/103547509/163093139-1592f35e-9a17-440e-bcdf-7d321b6a3020.png)
Thank you very much for your kind consideration and I am looking forward to your early reply.
Thanks & Regards,
Miaomiao Qi

**Comment by Juuuleuh-le-canare** [comment]
Hello,

I encounter the following error when running the  same command line

`find_reseau_grid  DZB1212-500212L006001_a.tif`
The image is a KH-9 image found on the USGS server.

`Finding grid points in DZB1212-500212L006001_a.tif...
Traceback (most recent call last):
  File "/home/avallet/anaconda3/envs/spymicmac/bin/find_reseau_grid", line 10, in <module>
    sys.exit(main())
  File "/home/avallet/anaconda3/envs/spymicmac/lib/python3.9/site-packages/spymicmac/tools/find_reseau_grid.py", line 23, in main
    find_reseau_grid(args.fn_img,
  File "/home/avallet/anaconda3/envs/spymicmac/lib/python3.9/site-packages/spymicmac/image.py", line 908, in find_reseau_grid
    _j, _i = find_cross(img, loc, cross, tsize=tsize)
  File "/home/avallet/anaconda3/envs/spymicmac/lib/python3.9/site-packages/spymicmac/image.py", line 678, in find_cross
    if max(this_z_corrs) > 4 and max(this_z_corrs)/min(this_z_corrs) > 1.15:
ValueError: max() arg is an empty sequence`

**Comment by iamdonovan** [comment]
This issue appears to have been fixed with the updates contained in #31 and v0.2.0.
