### ISSUE TITLE
Trouble with MicMac installation

### ISSUE THREAD

**Issue by Juuuleuh-le-canare** [iamdonovan/sPyMicMac#17]
[EDIT: Solved]
I managed to solve my problem by indicating the correct library to search for qt in the CMAKE command line:

cmake .. -DWITH_QT5=1 -DWERROR=0 -DWITH_CCACHE=OFF -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/qt5/plugins

--------------------------------

Hello,

I have trouble properly installing MicMac. Following the installation guidelines everything works fine until there:
`/home/bob/software/micmac/build:~$ cmake .. -DWITH_QT5=1 -DWERROR=0 -DWITH_CCACHE=OFF`

The following error is displayed:
-----------------------------------------
CMake Error at /home/avallet/anaconda3/envs/spatial_otb/conda-otb/lib/cmake/Qt5Xml/Qt5XmlConfig.cmake:14 (message):
  The imported target "Qt5::Xml" references the file

     "/home/avallet/anaconda3/envs/spatial_otb/conda-otb/lib/libQt5Xml.so.5.15.2"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/home/avallet/anaconda3/envs/spatial_otb/conda-otb/lib/cmake/Qt5Xml/Qt5XmlConfig.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /home/avallet/anaconda3/envs/spatial_otb/conda-otb/lib/cmake/Qt5Xml/Qt5XmlConfig.cmake:32 (_qt5_Xml_check_file_exists)
  /home/avallet/anaconda3/envs/spatial_otb/conda-otb/lib/cmake/Qt5Xml/Qt5XmlConfig.cmake:202 (_populate_Xml_target_properties)
  CMakeLists.txt:210 (find_package)`
------------------------------------

I am not very familiar with this, but from what i understand, the following file "libQt5Xml.so.5.15.2" is not found in the directory it searches in (the library of one of my conda environments). However libQt5Xml.so.5.15.3" (a newer version i assume) exists on my computer in the following directory "/usr/lib/x86_64-linux-gnu". 

I have tried to modify my environment variables accordingly by adding

-  "/usr" to C_MAKE_PREFIX

- /usr/lib/x86_64-linux-gnu to LD_LIBRARY_PATH

However the same arror displays when trying to run the cmake command line.
I am working with the following distribution: Description:    Ubuntu 22.04.2 LTS

Jules Michard,
Regards.

I have the following environment variables if this can be of any help:

declare -x BROWSER="/usr/lib/rstudio-server/bin/postback/rpostback-browser"
declare -x CLICOLOR_FORCE="1"
declare -x CMAKE_PREFIX_PATH="/usr:/home/avallet/anaconda3/envs/spatial_otb/conda-otb:/home/vallet/anaconda3/lib"
declare -x CONDA_BACKUP_ADDR2LINE="/home/avallet/anaconda3/envs/test-iota/bin/x86_64-conda-linux-gnu-addr2line"
declare -x CONDA_BACKUP_AR="/home/avallet/anaconda3/envs/test-iota/bin/x86_64-conda-linux-gnu-ar"
declare -x CONDA_BACKUP_AS="/home/avallet/anaconda3/envs/test-iota/bin/x86_64-conda-linux-gnu-as"
declare -x CONDA_BACKUP_BUILD="x86_64-conda-linux-gnu"
declare -x CONDA_BACKUP_CC="/home/avallet/anaconda3/envs/test-iota/bin/x86_64-conda-linux-gnu-cc"
declare -x CONDA_BACKUP_CC_FOR_BUILD="/home/avallet/anaconda3/envs/test-iota/bin/x86_64-conda-linux-gnu-cc"
declare -x CONDA_BACKUP_CFLAGS="-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/avallet/anaconda3/envs/test-iota/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/avallet/anaconda3/envs/test-iota/include"
declare -x CONDA_BACKUP_CMAKE_PREFIX_PATH="/home/avallet/anaconda3/envs/test-iota:/home/avallet/anaconda3/envs/test-iota/x86_64-conda-linux-gnu/sysroot/usr"
declare -x CONDA_BACKUP_CONDA_BUILD_SYSROOT="/home/avallet/anaconda3/envs/test-iota/x86_64-conda-linux-gnu/sysroot"
declare -x CONDA_BACKUP_CONDA_TOOLCHAIN_BUILD="x86_64-conda-linux-gnu"
declare -x CONDA_BACKUP_CONDA_TOOLCHAIN_HOST="x86_64-conda-linux-gnu"
declare -x CONDA_BACKUP_CPP="/home/avallet/anaconda3/envs/test-iota/bin/x86_64-conda-linux-gnu-cpp"
declare -x CONDA_BACKUP_CPPFLAGS="-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/avallet/anaconda3/envs/test-iota/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/avallet/anaconda3/envs/test-iota/include"
declare -x CONDA_BACKUP_CXX="/home/avallet/anaconda3/envs/test-iota/bin/x86_64-conda-linux-gnu-c++"
declare -x CONDA_BACKUP_CXXFILT="/home/avallet/anaconda3/envs/test-iota/bin/x86_64-conda-linux-gnu-c++filt"
declare -x CONDA_BACKUP_CXXFLAGS="-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/avallet/anaconda3/envs/test-iota/include -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/avallet/anaconda3/envs/test-iota/include"
declare -x CONDA_BACKUP_CXX_FOR_BUILD="/home/avallet/anaconda3/envs/test-iota/bin/x86_64-conda-linux-gnu-c++"
declare -x CONDA_BACKUP_DEBUG_CFLAGS="-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem /home/avallet/anaconda3/envs/test-iota/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem /home/avallet/anaconda3/envs/test-iota/include"
declare -x CONDA_BACKUP_DEBUG_CPPFLAGS="-D_DEBUG -D_FORTIFY_SOURCE=2 -Og -isystem /home/avallet/anaconda3/envs/test-iota/include -D_DEBUG -D_FORTIFY_SOURCE=2 -Og -isystem /home/avallet/anaconda3/envs/test-iota/include"
declare -x CONDA_BACKUP_DEBUG_CXXFLAGS="-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem /home/avallet/anaconda3/envs/test-iota/include -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem /home/avallet/anaconda3/envs/test-iota/include"
declare -x CONDA_BACKUP_ELFEDIT="/home/avallet/anaconda3/envs/test-iota/bin/x86_64-conda-linux-gnu-elfedit"
declare -x CONDA_BACKUP_GCC="/home/avallet/anaconda3/envs/test-iota/bin/x86_64-conda-linux-gnu-gcc"
declare -x CONDA_BACKUP_GCC_AR="/home/avallet/anaconda3/envs/test-iota/bin/x86_64-conda-linux-gnu-gcc-ar"
declare -x CONDA_BACKUP_GCC_NM="/home/avallet/anaconda3/envs/test-iota/bin/x86_64-conda-linux-gnu-gcc-nm"
declare -x CONDA_BACKUP_GCC_RANLIB="/home/avallet/anaconda3/envs/test-iota/bin/x86_64-conda-linux-gnu-gcc-ranlib"
declare -x CONDA_BACKUP_GPROF="/home/avallet/anaconda3/envs/test-iota/bin/x86_64-conda-linux-gnu-gprof"
declare -x CONDA_BACKUP_GXX="/home/avallet/anaconda3/envs/test-iota/bin/x86_64-conda-linux-gnu-g++"
declare -x CONDA_BACKUP_HOST="x86_64-conda-linux-gnu"
declare -x CONDA_BACKUP_LD="/home/avallet/anaconda3/envs/test-iota/bin/x86_64-conda-linux-gnu-ld"
declare -x CONDA_BACKUP_LDFLAGS="-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/home/avallet/anaconda3/envs/test-iota/lib -Wl,-rpath-link,/home/avallet/anaconda3/envs/test-iota/lib -L/home/avallet/anaconda3/envs/test-iota/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/home/avallet/anaconda3/envs/test-iota/lib -Wl,-rpath-link,/home/avallet/anaconda3/envs/test-iota/lib -L/home/avallet/anaconda3/envs/test-iota/lib"
declare -x CONDA_BACKUP_LD_GOLD="/home/avallet/anaconda3/envs/test-iota/bin/x86_64-conda-linux-gnu-ld.gold"
declare -x CONDA_BACKUP_NM="/home/avallet/anaconda3/envs/test-iota/bin/x86_64-conda-linux-gnu-nm"
declare -x CONDA_BACKUP_OBJCOPY="/home/avallet/anaconda3/envs/test-iota/bin/x86_64-conda-linux-gnu-objcopy"
declare -x CONDA_BACKUP_OBJDUMP="/home/avallet/anaconda3/envs/test-iota/bin/x86_64-conda-linux-gnu-objdump"
declare -x CONDA_BACKUP_RANLIB="/home/avallet/anaconda3/envs/test-iota/bin/x86_64-conda-linux-gnu-ranlib"
declare -x CONDA_BACKUP_READELF="/home/avallet/anaconda3/envs/test-iota/bin/x86_64-conda-linux-gnu-readelf"
declare -x CONDA_BACKUP_SIZE="/home/avallet/anaconda3/envs/test-iota/bin/x86_64-conda-linux-gnu-size"
declare -x CONDA_BACKUP_STRINGS="/home/avallet/anaconda3/envs/test-iota/bin/x86_64-conda-linux-gnu-strings"
declare -x CONDA_BACKUP_STRIP="/home/avallet/anaconda3/envs/test-iota/bin/x86_64-conda-linux-gnu-strip"
declare -x CONDA_BACKUP_build_alias="x86_64-conda-linux-gnu"
declare -x CONDA_BACKUP_host_alias="x86_64-conda-linux-gnu"
declare -x CONDA_DEFAULT_ENV="spatial_otb"
declare -x CONDA_EXE="/home/avallet/anaconda3/bin/conda"
declare -x CONDA_PREFIX="/home/avallet/anaconda3/envs/spatial_otb"
declare -x CONDA_PREFIX_1="/home/avallet/anaconda3"
declare -x CONDA_PROMPT_MODIFIER="(spatial_otb) "
declare -x CONDA_PYTHON_EXE="/home/avallet/anaconda3/bin/python"
declare -x CONDA_SHLVL="2"
declare -x CPL_ZIP_ENCODING="UTF-8"
declare -x DISPLAY=":0"
declare -x DQt5_ROOT="/usr"
declare -x EDITOR="vi"
declare -x GDAL_DATA="/home/avallet/anaconda3/envs/spatial_otb/conda-otb/share/gdal"
declare -x GDAL_DRIVER_PATH="disable"
declare -x GIT_ASKPASS="rpostback-askpass"
declare -x GSETTINGS_SCHEMA_DIR="/home/avallet/anaconda3/envs/spatial_otb/share/glib-2.0/schemas"
declare -x GSETTINGS_SCHEMA_DIR_CONDA_BACKUP=""
declare -x HISTCONTROL="ignoreboth"
declare -x HOME="/home/avallet"
declare -x LANG="fr_FR.UTF-8"
declare -x LC_NUMERIC="C"
declare -x LD_LIBRARY_PATH="/usr/lib/R/lib:/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/default-java/lib/server"
declare -x LESSCLOSE="/usr/bin/lesspipe %s %s"
declare -x LESSOPEN="| /usr/bin/lesspipe %s"
declare -x LN_S="ln -s"
declare -x LOGNAME="avallet"
declare -x LS_COLORS="rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:"
declare -x MAKE="make"
declare -x MPLENGINE="tkAgg"
declare -x OLDPWD="/usr"
declare -x OTB_APPLICATION_PATH="/home/avallet/anaconda3/envs/spatial_otb/conda-otb/lib/otb/applications:/home/avallet/anaconda3/envs/spatial_otb/conda-otb/lib/otb/applications"
declare -x PAGER="/usr/bin/pager"
declare -x PATH="/home/avallet/anaconda3/envs/spatial_otb/conda-otb/bin:/home/avallet/anaconda3/envs/spatial_otb/bin:/home/avallet/anaconda3/envs/spatial_otb/conda-otb/bin:/home/avallet/anaconda3/envs/spatial_otb/conda-otb/bin:/home/avallet/anaconda3/bin:/home/avallet/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/lib/rstudio-server/bin/quarto/bin:/usr/lib/rstudio-server/bin/postback/postback:/usr/lib/rstudio-server/bin/postback/postback:/usr/lib/rstudio-server/bin/postback/postback:/usr/lib/rstudio-server/bin/postback/postback:/usr/lib/rstudio-server/bin/postback/postback:/usr/lib/rstudio-server/bin/postback/postback:/usr/bin:/usr/bin:/usr/bin:/usr/bin:/usr/bin:/usr/bin:/usr/bin:/usr/bin:/usr/bin:/usr/bin:/usr/bin:/usr/bin"
declare -x PROJ_DATA="/home/avallet/anaconda3/envs/spatial_otb/share/proj"
declare -x PROJ_LIB="/home/avallet/anaconda3/envs/spatial_otb/conda-otb/share/proj:/home/avallet/anaconda3/envs/spatial_otb/share/proj"
declare -x PROJ_NETWORK="ON"
declare -x PROMPT_COMMAND="echo -ne \"\\033]0;\${PWD/#\${HOME}/~}\\007\""
declare -x PWD="/home/avallet/micmac/build"
declare -x PYTHONPATH="/home/avallet/anaconda3/envs/spatial_otb/conda-otb/lib/python:/home/avallet/anaconda3/envs/spatial_otb/conda-otb/lib/python"
declare -x RETICULATE_MINICONDA_ENABLED=""
declare -x RETICULATE_PYTHON_FALLBACK="/home/avallet/anaconda3/bin/python"
declare -x RMARKDOWN_MATHJAX_PATH="/usr/lib/rstudio-server/resources/mathjax-27"
declare -x RSTUDIO="1"
declare -x RSTUDIO_CHILD_PROCESS_PANE="terminal"
declare -x RSTUDIO_CLI_HYPERLINKS="true"
declare -x RSTUDIO_CONSOLE_COLOR="256"
declare -x RSTUDIO_CONSOLE_WIDTH="135"
declare -x RSTUDIO_HTTP_REFERER="http://157.136.249.10:8080/"
declare -x RSTUDIO_PANDOC="/usr/lib/rstudio-server/bin/quarto/bin/tools"
declare -x RSTUDIO_PROGRAM_MODE="server"
declare -x RSTUDIO_PROJ_NAME=""
declare -x RSTUDIO_R_MODULE=""
declare -x RSTUDIO_R_PRELAUNCH_SCRIPT=""
declare -x RSTUDIO_R_REPO=""
declare -x RSTUDIO_R_VERSION_LABEL=""
declare -x RSTUDIO_SESSION_ID="5deb81d4"
declare -x RSTUDIO_SESSION_PID="1643411"
declare -x RSTUDIO_SESSION_STREAM="avallet-d"
declare -x RSTUDIO_TERM="9E76B53C"
declare -x RSTUDIO_TERMINAL_HOOKS="/usr/lib/rstudio-server/resources/terminal/hooks"
declare -x RSTUDIO_USER_IDENTITY="avallet"
declare -x RSTUDIO_USER_IDENTITY_DISPLAY="avallet"
declare -x RSTUDIO_VERSION="2022.12.0+353"
declare -x RSTUDIO_WINUTILS="bin/winutils"
declare -x RS_PORT_TOKEN="61e1dc358d8e"
declare -x RS_RPOSTBACK_PATH="/usr/lib/rstudio-server/bin/rpostback"
declare -x RS_SERVER_RPC_SOCKET_PATH="/var/run/rstudio-server/rstudio-rserver/session-server-rpc.socket"
declare -x RS_SERVER_URL="http://157.136.249.10:8080/"
declare -x RS_SESSION_TMP_DIR="/var/run/rstudio-server/rstudio-rsession"
declare -x RS_SESSION_URL=""
declare -x R_BROWSER="xdg-open"
declare -x R_BZIPCMD="/bin/bzip2"
declare -x R_CLI_HAS_HYPERLINK_IDE_HELP="true"
declare -x R_CLI_HAS_HYPERLINK_IDE_RUN="true"
declare -x R_CLI_HAS_HYPERLINK_IDE_VIGNETTE="true"
declare -x R_DOC_DIR="/usr/share/R/doc"
declare -x R_GZIPCMD="/bin/gzip -n"
declare -x R_HOME="/usr/lib/R"
declare -x R_INCLUDE_DIR="/usr/share/R/include"
declare -x R_LIBS_SITE="/usr/local/lib/R/site-library/:/usr/lib/R/site-library:/usr/lib/R/library"
declare -x R_LIBS_USER="/home/avallet/R/x86_64-pc-linux-gnu-library/4.2"
declare -x R_PAPERSIZE="letter"
declare -x R_PAPERSIZE_USER="letter"
declare -x R_PDFVIEWER="/usr/bin/xdg-open"
declare -x R_PLATFORM="x86_64-pc-linux-gnu"
declare -x R_PRINTCMD="/usr/bin/lpr"
declare -x R_RD4PDF="times,inconsolata,hyper"
declare -x R_SESSION_TMPDIR="/mnt/disk/temp/Rtmpf3otVI"
declare -x R_SHARE_DIR="/usr/share/R/share"
declare -x R_STRIP_SHARED_LIB="strip --strip-unneeded"
declare -x R_STRIP_STATIC_LIB="strip --strip-debug"
declare -x R_SYSTEM_ABI="linux,gcc,gxx,gfortran,gfortran"
declare -x R_TEXI2DVICMD="/usr/bin/texi2dvi"
declare -x R_UNZIPCMD="/usr/bin/unzip"
declare -x R_ZIPCMD="/usr/bin/zip"
declare -x SED="/bin/sed"
declare -x SHLVL="12"
declare -x SSH_ASKPASS="rpostback-askpass"
declare -x TAR="/bin/tar"
declare -x TEMP="/mnt/disk/temp"
declare -x TERM="xterm-256color"
declare -x TMP="/mnt/disk/temp"
declare -x TMPDIR="/mnt/disk/temp"
declare -x USER="avallet"
declare -x XDG_DATA_DIRS="/usr/local/share:/usr/share:/var/lib/snapd/desktop"
declare -x _CE_CONDA=""
declare -x _CE_M=""
declare -x _REALHOME="/home/avallet"
declare -x _R_CHECK_COMPILATION_FLAGS_KNOWN_="-Wformat -Werror=format-security -Wdate-time"

**Comment by iamdonovan** [comment]
Closing this, as it is indicated to be solved by passing the path for QT5 to cmake:

> cmake .. -DWITH_QT5=1 -DWERROR=0 -DWITH_CCACHE=OFF -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/qt5/plugins
