### ISSUE TITLE
name is not a correct homologue prefix

### ISSUE THREAD

**Issue by cc863** [iamdonovan/sPyMicMac#34]
![1683092122626](https://github.com/iamdonovan/spymicmac/assets/100006248/eb59fed2-4bd9-4421-b985-ca8099d218fc)
![1683092139090](https://github.com/iamdonovan/spymicmac/assets/100006248/a91836f1-4148-4896-a4d9-c0fb8d61f45e)
![1683092153177](https://github.com/iamdonovan/spymicmac/assets/100006248/91d0777e-2bb5-4dd4-aef2-1209814a23f1)

**Comment by iamdonovan** [comment]
It looks like you only have a single image (DZB1210-500177L001001) in this folder. 

Stereophotogrammetry (what MicMac does) [requires at least two images](https://spymicmac.readthedocs.io/en/latest/tutorials/tealdeer.html#:~:text=For%20stereo%20processing%2C%20you%20need%20a%20minimum%20of%20two%20images.) - try downloading the next image in the acquisition (DZB1210-500177L002001), then re-running the pre-processing script.
