### ISSUE TITLE
Non rotation matrix has been used as a rotation

### ISSUE THREAD

**Issue by cc863** [iamdonovan/spymicmac#35]
An error occurred while running the last step Aperi in preprocess_kh9.py
![413e0cf1428919e396d7525176bb7827](https://github.com/iamdonovan/spymicmac/assets/100006248/2c2ed8ad-1b56-459d-acc0-3fdd566a7796)

**Comment by iamdonovan** [comment]
This isn't an error - it's a warning that seems to always come up when running AperiCloud. You should still be able to open the .ply file using CloudCompare or MeshLab.
