### ISSUE TITLE
   Required masq fo not exist in MasqImageIn

### ISSUE THREAD

**Issue by cc863** [iamdonovan/spymicmac#36]
I use Malt to compute a relative DEM and orthoimages,But I encountered this problem, how can I solve it
![image](https://github.com/iamdonovan/spymicmac/assets/100006248/9e006569-959a-4130-a30f-eb787e826d73)
![96652febe64868687901f06a1ed9aa9a](https://github.com/iamdonovan/spymicmac/assets/100006248/125cb61e-ca9e-42b8-9547-ec1b9d03ab1b)

**Comment by cc863** [comment]
May I ask what is the name and folder of the use Malt to compute a relative DEM and orthoimages? Where can I download the files required for finding GCPs and iteratively refining the orientation, and what are the requirements for size and file placement @iamdonovan

**Comment by iamdonovan** [comment]
Did you try running the command without the `MasqImGlob` part? This is intended for images that have parts of the frame or fiducial markers within the part of the image (see [here](https://spymicmac.readthedocs.io/en/latest/tutorials/micmac_processing/tapioca.html#creating-a-mask) for a bit more information).
