### ISSUE TITLE
zero Division Error: division by zero

### ISSUE THREAD

**Issue by cc863** [iamdonovan/spymicmac#39]
Do the row and column numbers of the reference files Landsat and DEM need to be the same, and do they all need to cover the kh-9 image? Why does this problem always occur![4a49b878819e529fc7c22b82d19f1a19](https://github.com/iamdonovan/spymicmac/assets/100006248/eceee008-941e-4d51-8d1a-66fcbad187d4)

**Comment by iamdonovan** [comment]
What is the full command that you have used to run `register_ortho.py` that triggers this error?

**Comment by cc863** [comment]
$ python register_ortho.py Ortho-MEC-Relative/Orthophotomosaic.tif Landsat.tif MEC-Relative/Z_Num6_DeZoom8_STD-MALT.tif DEM.tif

**Comment by cc863** [comment]
> What is the full command that you have used to run `register_ortho.py` that triggers this error?

$ python register_ortho.py Ortho-MEC-Relative/Orthophotomosaic.tif Landsat.tif MEC-Relative/Z_Num6_DeZoom8_STD-MALT.tif DEM.tif

**Comment by cc863** [comment]
@iamdonovan  python register_ortho.py Ortho-MEC-Relative/Orthophotomosaic.tif Landsat.tif MEC-Relative/Z_Num6_DeZoom8_STD-MALT.tif DEM.tif
