### ISSUE TITLE
ram memory error?

### ISSUE THREAD

**Issue by hazemmahmoud88** [iamdonovan/sPyMicMac#4]
Hello,

How to overcome this error for hexagon joining:

Unable to allocate 19.2 GiB for an array with shape (35515, 72718) and data type float 64

Regards,
Hazem

**Comment by gyp-1991-gq** [comment]
Did you succeed? Can this be geometrically corrected for the KH-9? Does the final output image have a projection?

Regards,
Yongpeng Gao

**Comment by hazemmahmoud88** [comment]
Hello Yong,

Unfortunately I did not succeed on windows computer, I am actually now trying to run spymicmac on a linux machine with better spects to see if I will face the same problem.

How far are you In your workflow and what do you use?

Regards,
Hazem

**Comment by gyp-1991-gq** [comment]
"Unable to allocate 19.2 GiB for an array with shape (35515, 72718) and data type float 64" means that the data is too large and your computer has too little memory to run.

**Comment by hazemmahmoud88** [comment]
Yes, correct I agree. I am trying to find a workaround using another stronger computer. Is there a workflow for KH4 images?

**Comment by gyp-1991-gq** [comment]
DEMs can be extracted by the HEXIMAP tool. However, this tool requires the input of a KH-9 image that has been geometrically corrected. Therefore, I wonder if this Python package can be implemented.

**Comment by hazemmahmoud88** [comment]
I just looked into heximap, its built on matlab. Its also focus on KH-9 but my main objective is KH-4. Do you mean by geometrically corrected to be georeferenced?

Also I recommend you to use ASP stereo pipeline by NASA

**Comment by gyp-1991-gq** [comment]
yes, Is there any other way?

**Comment by gyp-1991-gq** [comment]
I'm good at python

**Comment by hazemmahmoud88** [comment]
https://github.com/NeoGeographyToolkit/StereoPipeline

**Comment by iamdonovan** [comment]
> Hello,
> 
> How to overcome this error for hexagon joining:
> 
> Unable to allocate 19.2 GiB for an array with shape (35515, 72718) and data type float 64
> 
> Regards, Hazem

This error comes up because your computer doesn't have the memory to create the array - if you're running this on a laptop, that's not a big surprise. 

You can try downsampling the images first, which will reduce the size needed; I've opened this as a new issue ( #5 ), and try to re-implement the numpy call to avoid using the default float64 datatype.
